#' @title Get the predicted cluster label and predicted outcome using the gene expression of validation dataset and the ogClust_GM model from training data
#' @param mod ogClust_GM model from discovery/training data, generated by ogClust_GM() or ogClust_GM.surv()
#' @param K Number of clusters
#' @param D.test Gene expression of validation/testing data (n*p matrix)
#' @param X.test covariate matrix of discovery/training data (n*q matrix)
#' @return a list with five components
#' \itemize{
#' \item{y.pred: }{predicted outcome}
#' \item{clus: }{predicted cluster label}
#' }
#' @export
#'
#' @examples
#' \dontrun{
#' data('GSE47460_GPL14550') #load lung dataset
#' X<-GSE47460_GPL14550$Covariates
#' G<-GSE47460_GPL14550$Expression
#' Y<-GSE47460_GPL14550$outcome
#'
#'   g.mean<-apply(G,1,mean)
#'   cut.mean=quantile(g.mean,probs=0.5)
#'   G=G[g.mean>cut.mean,] # remove 50% lowest mean expression genes
#'   g.sd=apply(G,1, sd)
#'   cut.sd=quantile(g.sd,probs=0.5)
#'   G=G[g.sd>=cut.sd,] # further remove 50% lowest variance genes
#'   G<-t(G)
#'   G<-scale(G)
#'   number of subjects
#'   n=nrow(G)
#'   # number of genes
#'   NG=ncol(G)
#'   # number of covariates
#'   np=ncol(X)
#'   # number of clusters
#'   K=3
#'   # tuning parameter
#'   lambda=0.001
#'   fit.res<-ogClust_GM(n=n, K=K, np=np, NG=NG, lambda=lambda,
#'                     alpha=1, G=G, Y=Y, X=X,theta_int=theta_int)
#' #predict for the validation data
#' data('GSE47460_GPL6480')
#' G.test<-t(GSE47460_GPL6480$Expression)
#' X.test<-GSE47460_GPL6480$Covariates
#' index<-match(colnames(G),colnames(G.test))
#' G.test<-G.test[,index]
#' mod.predict<-predict_GM(fit.res,K = 3,D.test =G.test,X.test =X.test)
#'}

predict_GM<-function(mod,K,D.test,X.test){
  beta_est=mod$par$beta
  gamma_est_matrix=mod$par$gamma
  beta0_est=mod$par$beta0
  sigma2_est=mod$par$sigma2

  D.test.add = cbind(1, D.test)
  pai_est.num = sapply(1:K, function(k) exp(D.test.add %*% gamma_est_matrix[,  k, drop = F])/rowSums(exp(D.test.add %*% gamma_est_matrix)))

  cluster.test<-apply(pai_est.num,1,which.max)

  intercept<-rep(NA,nrow(X.test))
  for(i in 1:K){
    intercept[which(cluster.test==i)]<-beta0_est[i]
  }
  pred.test<-as.matrix(scale(X.test)) %*% beta_est+intercept

  res<-list(Y=pred.test,clus=cluster.test)
  return(res)
}

